<?php
/**
 * Created by PhpStorm.
 * User: FOCUS
 * Date: 2018/11/1
 * Time: 17:55
 */

namespace frontend\controllers;


use yii\web\Controller;

class FrontendController extends Controller
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}