<?php
/**
 * Created by PhpStorm.
 * User: FOCUS
 * Date: 2018/11/12
 * Time: 21:29
 */

namespace frontend\controllers;


use common\components\Common;
use yii\web\Controller;
use Yii;

class PublicController extends Controller
{
    private $exceptRoute = ['send-mobile-code'];

    public function beforeAction($action)
    {
        /**
         * 如果该路由在 $this->exceptRoute中，这验证csrf
         */
        if (in_array($action->id, $this->exceptRoute)) {
            return parent::beforeAction($action);
        }
        return true; // TODO: Change the autogenerated stub
    }

    public function actionSendMobileCode()
    {
        if (!Common::sendRegisterCode()) {
            return false;
        }
        return true;
    }


    public function actionSendMobileCodeForget()
    {
        Common::sendCodeForget();
        return true;
    }


    public function actionUpload()
    {
        $file = $_FILES;
        $extend = explode('/', $file['file']['type'])[1];
        $path = 'static/images/order/' . time() . rand(1000, 9999) . '.' . $extend;
        if (move_uploaded_file($file['file']['tmp_name'], $path)) {
            return [
                'code' => 0,
                'msg' => 0,
                'data' => ['src' => $path]
            ];
        }
        return $array = [
            'code' => 1,
            'msg' => 0,
            'data' => ['src' => '']
        ];
    }

    public function actionDelPic()
    {
        $path = Yii::$app->request->post('path');
        if (preg_match('/\.\.\//', $path)) {
            return false;
        }
        if (preg_match('/static\/images/', $path)) {
            if (unlink($path)) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }
}