<?php

namespace backend\models;

use common\libs\Constants;
use Yii;

/**
 * This is the model class for table "{{%order}}".
 *
 * @property string $id
 * @property string $admin_id 導師用戶id
 * @property string $user_id 預約用戶id
 * @property int $year
 * @property int $month
 * @property int $day
 * @property int $time
 * @property int $price
 * @property int $status 是否預約1否；2是；3取消；
 * @property int $delete
 */
class Order extends \common\models\Order
{
    public static function deletes()
    {
        $id = yii::$app->getRequest()->get('id');
        $model = self::findOne(['id' => $id]);
        $model->scenario='delete';
        if ($model->status != self::STATUS_WAIT_ORDER) {
            return false;
        }
        $model->delete=self::DELETED;
        if (!$model->save()) {
            return false;
        }
        return true;
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->start_time = date("Y-m-d H:i", $this->start_time);
        $this->end_time = date("Y-m-d H:i", $this->end_time);
    }
}
