<?php
/**
 * Created by PhpStorm.
 * User: FOCUS
 * Date: 2018/11/29
 * Time: 21:44
 */

namespace frontend\models;


class Pay extends \common\models\Pay
{
    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->created_at=date('Y-m-d H:i',$this->created_at);
        $this->status=self::getStatusItems($this->status);
        $this->pay_type=self::getPayTypeItems($this->pay_type);
    }
}